/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_PRODUCT_VERSION		"1.6.1"

#define SVN_REVISION			671
#define SVN_REVISION_STRING		"671"
#define SVN_FILE_VERSION		1,6,1,671
#define SVN_FILE_VERSION_STRING	"1.6.1.671"

#endif //_INCLUDE_SVN_VERSION_H_
