/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_PRODUCT_VERSION		"1.4.2"

#define SVN_REVISION			414
#define SVN_REVISION_STRING		"414"
#define SVN_FILE_VERSION		1,4,2,414
#define SVN_FILE_VERSION_STRING	"1.4.2.414"

#endif //_INCLUDE_SVN_VERSION_H_
