/**
 * vim: set ts=4 sw=4 tw=99 noet :
 * ======================================================
 * Metamod:Source
 * Copyright (C) 2004-2010 AlliedModders LLC and authors.
 * All rights reserved.
 * ======================================================
 *
 * This software is provided 'as-is', without any express or implied warranty.
 * In no event will the authors be held liable for any damages arising from 
 * the use of this software.
 * 
 * Permission is granted to anyone to use this software for any purpose, 
 * including commercial applications, and to alter it and redistribute it 
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not 
 * claim that you wrote the original software. If you use this software in a 
 * product, an acknowledgment in the product documentation would be 
 * appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 * misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 */

#ifndef _INCLUDE_METAMOD_VERSION_INFORMATION_H_
#define _INCLUDE_METAMOD_VERSION_INFORMATION_H_

/**
 * @file Contains Metamod version information.
 * @brief This file will redirect to an autogenerated version if being compiled via
 * the build scripts.
 */

#if defined MMS_GENERATED_BUILD
#include <metamod_version_auto.h>
#else
#define MMS_BUILD_STRING		"-pdev"
#define MMS_BUILD_UNIQUEID		"701:46ea970e0eb6" MMS_BUILD_STRING
#define MMS_FULL_VERSION		"1.9.0" MMS_BUILD_STRING
#define MMS_FILE_VERSION		1,9,0,0
#endif

#endif /* _INCLUDE_METAMOD_VERSION_INFORMATION_H_ */
