/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_PRODUCT_VERSION		"1.6.2"

#define SVN_REVISION			703
#define SVN_REVISION_STRING		"703"
#define SVN_FILE_VERSION		1,6,2,703
#define SVN_FILE_VERSION_STRING	"1.6.2.703"

#endif //_INCLUDE_SVN_VERSION_H_
