/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_MMS_VERSION_H_
#define _INCLUDE_MMS_VERSION_H_

#define MMS_BUILD_STRING     "-dev"
#define MMS_BUILD_UNIQUEID   "654:b91f45b92fe5" MMS_BUILD_STRING
#define MMS_FULL_VERSION    "1.8.0" MMS_BUILD_STRING
#define MMS_FILE_VERSION    1,8,0,0

#endif //_INCLUDE_MMS_VERSION_H_

