/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_PRODUCT_VERSION		"1.7.0"

#define SVN_REVISION			705
#define SVN_REVISION_STRING		"705"
#define SVN_FILE_VERSION		1,7,0,705
#define SVN_FILE_VERSION_STRING	"1.7.0.705"

#endif //_INCLUDE_SVN_VERSION_H_
