/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define MMS_BUILD_STRING     "$BUILD_STRING$"
#define MMS_BUILD_UNIQUEID   "$BUILD_ID$" MMS_BUILD_STRING
#define SVN_FULL_VERSION    "$PMAJOR$.$PMINOR$.$PREVISION$" MMS_BUILD_STRING
#define SVN_FILE_VERSION    $PMAJOR$,$PMINOR$,$PREVISION$,0

#endif //_INCLUDE_SVN_VERSION_H_

