/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_MMS_VERSION_H_
#define _INCLUDE_MMS_VERSION_H_

#define MMS_BUILD_STRING     "-dev"
#define MMS_BUILD_UNIQUEID   "610:1faa00e69cbb" MMS_BUILD_STRING
#define MMS_FULL_VERSION    "1.7.0" MMS_BUILD_STRING
#define MMS_FILE_VERSION    1,7,0,0

#endif //_INCLUDE_MMS_VERSION_H_

