/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_MMS_VERSION_H_
#define _INCLUDE_MMS_VERSION_H_

#define MMS_BUILD_STRING     "-dev"
#define MMS_BUILD_UNIQUEID   "648:f1c248baeed8" MMS_BUILD_STRING
#define MMS_FULL_VERSION    "1.7.1" MMS_BUILD_STRING
#define MMS_FILE_VERSION    1,7,1,0

#endif //_INCLUDE_MMS_VERSION_H_

